name: WorldDownloaderV2
version: '0.0.1'
main: dev.twme.worldDownloaderV2.WorldDownloaderV2
api-version: '1.21'
authors: [ TWME ]
libraries:
  - io.minio:minio:8.5.12
  - net.lingala.zip4j:zip4j:2.11.5
commands:
  downloadworld:
    description: download the world
    usage: /downloadworld
    permission: worlddownloader.use
permissions:
  worlddownloader.use:
    description: allow the player to download the world
    default: true